<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPAMYERW0037" name="runner.CalculatorDivDoubleTest" tests="1" failures="0" timestamp="06 Jun 2017 13:14:05 GMT" time="0.001" errors="1">
  <testcase name="testDivDoubleByZero" time="0.001" classname="runner.CalculatorDivDoubleTest">
    <error type="org.testng.TestException" message="
Method CalculatorDivDoubleTest.testDivDoubleByZero()[pri:0, instance:runner.CalculatorDivDoubleTest@2ed94a8b] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method CalculatorDivDoubleTest.testDivDoubleByZero()[pri:0, instance:runner.CalculatorDivDoubleTest@2ed94a8b] should have thrown an exception of type class java.lang.NumberFormatException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testDivDoubleByZero -->
</testsuite> <!-- runner.CalculatorDivDoubleTest -->
